/**
 * Emits the reference-data seed migration from the same modules the pricing
 * engine is tested against, so the database can never drift from the code.
 * Re-run after editing the reference data:  node --import ./test/resolve-ts.mjs test/gen-seed.ts
 */
import { writeFileSync } from "node:fs";
import { BRANDS } from "../lib/pricing/brands";
import { DEFAULT_SETTINGS, GRADES, LADDER_DEPTHS, LADDER_MONTHS, PROFILES, SETTINGS_VERSION } from "../lib/pricing/constants";
import { CATEGORIES, SUB_CATEGORIES } from "../lib/pricing/sub-categories";

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const n = (v: number | null | undefined) => (v == null ? "null" : String(v));
const out: string[] = [
  "-- GENERATED by test/gen-seed.ts from lib/pricing/* — do not edit by hand.",
  "",
  "insert into public.settings (version, fx, blended_rate, duty_per_kg, sorting_per_piece, input_tax_rate, input_tax_recover, sales_tax, target_gp, rejected_share, bulk_recovery, charm_step, charm_end, min_price, ladder_depths, ladder_months, brand_feedback_enabled, high_value_threshold, note) values",
  `  (${SETTINGS_VERSION}, ${DEFAULT_SETTINGS.fx}, ${DEFAULT_SETTINGS.blendedRate}, ${DEFAULT_SETTINGS.dutyPerKg}, ${DEFAULT_SETTINGS.sortingPerPiece}, ${DEFAULT_SETTINGS.inputTaxRate}, ${DEFAULT_SETTINGS.inputTaxRecover}, ${DEFAULT_SETTINGS.salesTax}, ${DEFAULT_SETTINGS.targetGP}, ${DEFAULT_SETTINGS.rejectedShare}, ${DEFAULT_SETTINGS.bulkRecovery}, ${DEFAULT_SETTINGS.charmStep}, ${DEFAULT_SETTINGS.charmEnd}, ${DEFAULT_SETTINGS.minPrice}, array[${["full","md1","md2","md3"].map(s=>LADDER_DEPTHS[s as keyof typeof LADDER_DEPTHS]).join(", ")}]::numeric[], array[${["full","md1","md2","md3"].map(s=>LADDER_MONTHS[s as keyof typeof LADDER_MONTHS]).join(", ")}], ${DEFAULT_SETTINGS.brandFeedbackEnabled}, ${DEFAULT_SETTINGS.highValueThreshold}, 'Initial constants from the build specification');`,
  "",
  "insert into public.grades (code, name, multiplier, share_of_intake, sort_order) values",
  GRADES.map(g => `  (${q(g.code)}, ${q(g.name)}, ${g.multiplier}, ${g.shareOfIntake}, ${g.sortOrder})`).join(",\n") + ";",
  "",
  "insert into public.profiles (code, name, pulled_share, vol_full, vol_promo, vol_md1, vol_md2, vol_md3) values",
  PROFILES.map(p => `  (${q(p.code)}, ${q(p.name)}, ${p.pulledShare}, ${p.volFull}, ${p.volPromo}, ${p.volMd1}, ${p.volMd2}, ${p.volMd3})`).join(",\n") + ";",
  "",
  "insert into public.categories (slug, name, sort_order) values",
  CATEGORIES.map(c => `  (${q(c.slug)}, ${q(c.name)}, ${c.sortOrder})`).join(",\n") + ";",
  "",
  "insert into public.sub_categories (slug, category_slug, name, weight_kg, profile_code, value_index, measure_type, market_ceiling, per_piece_cost, per_piece_share, active) values",
  SUB_CATEGORIES.map(s => `  (${q(s.slug)}, ${q(s.categorySlug)}, ${q(s.name)}, ${s.weightKg}, ${q(s.profileCode)}, ${s.valueIndex}, ${q(s.measureType)}, ${n(s.marketCeiling)}, ${n(s.perPieceCost)}, ${s.perPieceShare}, ${s.active})`).join(",\n") + ";",
  "",
  "-- Only the brands named in the spec. Import Khazanay_brand_tiers.csv for the full 384.",
  "insert into public.brands (name, tier, active) values",
  BRANDS.map(b => `  (${q(b.name)}, ${q(b.tier)}, ${b.active})`).join(",\n") + ";",
  "",
  "-- The five physical outlets are not named in the spec; add them in the dashboard or a later migration.",
  "insert into public.outlets (name, is_online) values ('Online', true);",
  "",
];
const path = "supabase/migrations/20260907190100_pricing_seed.sql";
writeFileSync(path, out.join("\n"));
console.log(`${path}: settings 1, grades ${GRADES.length}, profiles ${PROFILES.length}, categories ${CATEGORIES.length}, sub_categories ${SUB_CATEGORIES.length}, brands ${BRANDS.length}`);
